### PR TITLE
Add ENVied instead of Figaro

### LINKED ISSUE #206: Secrets vs Figaro
Which one should we use since rails 4.1? I started using in my private project [secrets](http://guides.rubyonrails.org/4_1_release_notes.html#config-secrets-yml) and it just works.

pros for secrets:
* built-in
* default way to provide `secret_key_base`
* default way to provide credentials for production `database.yml`

cons:
* access only via `Rails.application.secrets` vs shorter `Figaro.env` and `ENV` in Figaro

Any thoughts?

### PR DESCRIPTION
**Pull request by jandudulski**
Closes #206

[Review on Reviewable](https://reviewable.io/reviews/monterail/guidelines/236)

### CODE REVIEW

**Comment by teamon** [comment]
@jandudulski I think a short note about default values and different environment could be useful (i.e. "how to use envied properly") :)

**Comment by jandudulski** [comment]
> default values

Added.

> different environment 

Environment for different environment. That sounds weird. What we do is actually just using ruby for dynamic rules in Envfile, based on RACK_ENV/RAILS_ENV value. I'm not sure if this should be described here.

> how to use envied properly

Smells like a blog post.

**Comment by teamon** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/monterail/guidelines/236)

**Comment by teamon** [comment]
Blog post, oh yeah!

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/monterail/guidelines/236)

**Pull request merged**
